# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e3602abf4a72913918b527315dab20c0c0f8404d5cb60b57e26e86b97162bb1e4c31240b40ec139cdaa7e329b30144cf4db083ab88a5b7f53bffbba036f679f

test:
  secret_key_base: b7311e6c7872ca67759a27ed491663dc2f420bbe5f419ad06d7eac6eafaf61ea42624945a4f0eac9534fa8eaeef9928cd4a47a5092af345bf200e3cef85086bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
